<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:site" content="@animejam_staff">
<meta name="twitter:creator" content="@animejam_staff">
<meta name="twitter:title" content="<?php echo PAGE_TITLE;?>｜<?php include($_SERVER['DOCUMENT_ROOT'] .  "/include/common/title.inc");?>">
<meta name="twitter:description" content="<?php include($_SERVER['DOCUMENT_ROOT'] .  "/include/common/description.inc");?>">
<meta name="twitter:url" content="<?php echo (empty($_SERVER["HTTPS"]) ? "http://" : "https://") . $_SERVER["HTTP_HOST"] . $_SERVER["REQUEST_URI"]; ?>">
<meta name="twitter:image" content="<?php include($_SERVER['DOCUMENT_ROOT'] . "/include/common/og-image.inc"); ?>">
